version: '3.9'

services:
  postgres:
    image: postgres:bookworm
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB 
  slackbot:
    depends_on:
      - postgres
    build: .
    environment:
      - RH_USERNAME
      - RH_PASSWORD
      - SLACK_BOT_TOKEN
      - SLACK_USER_ID
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    